name: Build and Push Docker Image
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Image Name
        id: set_image_name
        run: |
           echo "::set-output name=IMAGE_NAME::ghcr.io/${{ github.repository_owner }}/docker-image:latest"
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.set_image_name.outputs.IMAGE_NAME }}

